from agno.agent import Agent
from agno.models.together import Together
from dotenv import load_dotenv
import os

load_dotenv()

# Define the review generation agent
review_generation_agent = Agent(
    name="review-generation-agent",
    model=Together(id="meta-llama/Llama-3.3-70B-Instruct-Turbo-Free", api_key=os.getenv("TOGETHER_API_KEY")),
    description=
    '''
        You are a review generation agent that will generate a comprehensive literature review of research papers using 
        the provided metadata and summaries of papers generated by the Summarization Agent.
    ''',
    instructions=[
        "Generate a literature review using the metadata, abstracts, and summaries of the papers from the Summarization Agent.",
        "The final response should include the literature review of each research paper in a separate paragraph.",
        "Each paper review should start with the title of the paper as a subheading, along with metadata of that paper at the beginning."
        "Follow the following format for the metadata of each paper in normal text displaying each metadata item on a new line:",
            "**Authors**: [Authors of the Paper]",
            "**Publication Date**: [Date of Publication]",
            "**Keywords**: [Keywords of the Paper]",
            "**PDF Path**: [Path to the Downloaded Paper]",
        "Display each item of the metadata on a new line.",
        "Follow the following format for the review of each paper in italic text:",
            "**Review**: *[Literature review of the Paper]*",
        "Do not include a Literature Review heading in the response.",
        "Include a conclusion section providing a combined summary of all papers.",
        "Include a references section at the end of the literature review which includes a list of citations with source links.",
        "Generate the literature review by processing the summaries of the papers in smaller chunks instead of one long response."
        "Important: You final response must be in JSON format with the following structure:",
            "{"
            "    'papers': ["
            "        {"
            "            'title': 'Title of the Paper',"
            "            'authors': 'Authors of the Paper',"            
            "            'abstract': 'Abstract of the Paper',"
            "            'publication_date': 'Date of Publication',"
            "            'keywords': 'Keywords of the Paper',"
            "            'source_link': 'Source Link of the Paper',"
            "            'summary': 'Summary of the Paper',"
            "            'review': 'Literature Review of the Paper'",
            "            'pdf_path': 'Path to the Downloaded Paper'"
            "        },"
            "        {...}"
            "    ]",
            "    'conclusion': 'Combined summary of all papers',"
            "    'references': 'List of citations with source links'"
            "}"
        "The above JSON response must include all papers with required information, conclusion, and references.",
        "The response MUST be in proper JSON format with keys and values in double quotes.",
        "The final response MUST not include anything else other than the JSON response."
    ],
    markdown=True,
    show_tool_calls=True,
    debug_mode=True
)
